service: aws-middy-sequalize
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  environment:
    DB_HOST: ${env:DB_HOST}
    DB_NAME: ${env:DB_NAME}
    DB_USERNAME: ${env:DB_USERNAME}
    DB_PASSWORD: ${env:DB_PASSWORD}

plugins:
  - serverless-offline
useDotenv: true

functions:
  getPost:
    handler: functions/post.list
    events:
      - http:
          path: /posts
          method: get
  createPost:
    handler: functions/post.create
    events:
      - http:
          path: /posts
          method: post
